# ######################################################
## Board Specific
# ######################################################
CONFIG_ZMK_KEYBOARD_NAME="taro"

# Screen config
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Enable mouse
CONFIG_ZMK_POINTING=y
